const ROOTS = {
  AUTH: "/auth",
  COURSE: "/course",
  USER: "/user",
  GROUP: "/group",
  ANNOUNCEMENT: "/announcement",
  SCORE_WEIGHT: "/score-weight",
  LESSON_PLAN: "/lesson-plan",
  RUBRIC: "/rubric",
  ACTIVITY: "/activity",
  LEANING_ACTIVITY: "/learning-activity",
  STUDENT: "/student",
  MAPPING: "/mapping",
  STUDENT_ACTIVITY: "/student-activity",
  STUDENT_LEARNING_ACTIVITY: "/student-learning-activity",
  STUDENT_ACTIVITY_GROUP: "/student-activity-group",
  PORTFOLIO_PERSONAL: "/portfolio-personal",
  PORTFOLIO_EDUCATION: "/portfolio-education",
  PORTFOLIO_TRAINING: "/portfolio-training",
  PORTFOLIO_CERTIFICATE: "/portfolio-certificate",
  PORTFOLIO_INTERNSHIP: "/portfolio-internship",
  PORTFOLIO_AWARD: "/portfolio-award",
  PORTFOLIO_THESIS: "/portfolio-thesis",
  PORTFOLIO_ACTIVITY: "/portfolio-activity",
  PORTFOLIO_SKILL: "/portfolio-skill",
  STUDENT_LEARNING_ACTIVITY_GROUP: "/student-learning-activity-group",
  GRADEBOOK: "/gradebook",
  COURSE_MATERIAL: "/course-material",
  EVALUATION: "/evaluation",
  PORTFOLIO: "/portfolio",
};

export const endpoints = {
  auth: {
    root: ROOTS.AUTH,
    logout: `${ROOTS.AUTH}/logout`,
    login: `${ROOTS.AUTH}/login`,
  },
  group: {
    root: ROOTS.GROUP,
    acceptInvite: `${ROOTS.GROUP}/accept-invite`,
    validateInvite: `${ROOTS.GROUP}/validate-invite`,
  },
  course: {
    root: ROOTS.COURSE,
    list: `${ROOTS.COURSE}/list`,
    clo: `${ROOTS.COURSE}/clo`,
    plo: `${ROOTS.COURSE}/plo/list`,
    schedule: `${ROOTS.COURSE}/schedule`,
  },
  user: {
    student: `${ROOTS.USER}/student`,
    teacher: `${ROOTS.USER}/teacher`,
    root: ROOTS.USER,
    detail: (id: string) => `${ROOTS.USER}/?id=${id}`,
  },
  announcement: {
    root: ROOTS.ANNOUNCEMENT,
  },
  score_weight: {
    root: ROOTS.SCORE_WEIGHT,
    options: `${ROOTS.SCORE_WEIGHT}/options`,
  },
  lesson_plan: {
    root: ROOTS.LESSON_PLAN,
    options: `${ROOTS.LESSON_PLAN}/options`,
    student: `${ROOTS.LESSON_PLAN}/student`,
  },
  rubric: {
    root: ROOTS.RUBRIC,
    "shared-rubric": `${ROOTS.RUBRIC}/shared-rubric`,
    "shared-rubric-detail": `${ROOTS.RUBRIC}/shared-rubric/detail`,
  },
  activity: {
    root: ROOTS.ACTIVITY,
    list: `${ROOTS.ACTIVITY}/list`,
    student: `${ROOTS.ACTIVITY}/student/detail`,
    options: `${ROOTS.ACTIVITY}/options`,
    submitted_list: `${ROOTS.ACTIVITY}/submitted/list`,
  },
  learning_activity: {
    root: ROOTS.LEANING_ACTIVITY,
    list: `${ROOTS.LEANING_ACTIVITY}/list`,
    student: `${ROOTS.LEANING_ACTIVITY}/student/detail`,
    options: `${ROOTS.LEANING_ACTIVITY}/options`,
    submitted_list: `${ROOTS.LEANING_ACTIVITY}/submitted/list`,
  },
  student: {
    root: ROOTS.STUDENT,
    list: `${ROOTS.STUDENT}/list`,
    course: `${ROOTS.STUDENT}/course/list`,
    classwork: `${ROOTS.STUDENT}/classwork/list`,
    all_classwork: `${ROOTS.STUDENT}/all/classwork/list`,
    submit: {
      activity: `${ROOTS.STUDENT}/submit/activity`,
      learning_activity: `${ROOTS.STUDENT}/submit/learning-activity`,
    },
    calendar: `${ROOTS.STUDENT}/calendar`,
  },
  mapping: {
    root: ROOTS.MAPPING,
    activity: {
      root: `${ROOTS.MAPPING}/activity`,
      validate: `${ROOTS.MAPPING}/activity/validate`,
    },
    learning_activity: `${ROOTS.MAPPING}/learning-activity`,
  },
  student_activity: {
    grade: `${ROOTS.STUDENT_ACTIVITY}/grade`,
    bookmark: `${ROOTS.STUDENT_ACTIVITY}/bookmark`,
  },
  student_learning_activity: {
    grade: `${ROOTS.STUDENT_LEARNING_ACTIVITY}/grade`,
    bookmark: `${ROOTS.STUDENT_LEARNING_ACTIVITY}/bookmark`,
  },
  student_activity_group: {
    root: ROOTS.STUDENT_ACTIVITY_GROUP,
    all: `${ROOTS.STUDENT_ACTIVITY_GROUP}/all`,
    without_group: `${ROOTS.STUDENT_ACTIVITY_GROUP}/without-group`,
  },
  portfolio_personal: {
    root: ROOTS.PORTFOLIO_PERSONAL,
    detail: (id: string) => `${ROOTS.PORTFOLIO_PERSONAL}/${id}`,
  },
  portfolio_education: {
    root: ROOTS.PORTFOLIO_EDUCATION,
    list: `${ROOTS.PORTFOLIO_EDUCATION}/`,
    detail: (id: number) => `${ROOTS.PORTFOLIO_EDUCATION}/${id}`,
  },
  portfolio_training: {
    root: ROOTS.PORTFOLIO_TRAINING,
    list: `${ROOTS.PORTFOLIO_TRAINING}/`,
    detail: (id: number) => `${ROOTS.PORTFOLIO_TRAINING}/${id}`,
  },
  portfolio_certificate: {
    root: ROOTS.PORTFOLIO_CERTIFICATE,
    list: `${ROOTS.PORTFOLIO_CERTIFICATE}/`,
    detail: (id: number) => `${ROOTS.PORTFOLIO_CERTIFICATE}/${id}`,
  },
  portfolio_internship: {
    root: ROOTS.PORTFOLIO_INTERNSHIP,
    list: `${ROOTS.PORTFOLIO_INTERNSHIP}/`,
    detail: (id: number) => `${ROOTS.PORTFOLIO_INTERNSHIP}/${id}`,
  },
  portfolio_award: {
    root: ROOTS.PORTFOLIO_AWARD,
    list: `${ROOTS.PORTFOLIO_AWARD}/`,
    detail: (id: number) => `${ROOTS.PORTFOLIO_AWARD}/${id}`,
  },
  portfolio_thesis: {
    root: ROOTS.PORTFOLIO_THESIS,
    list: `${ROOTS.PORTFOLIO_THESIS}/`,
    detail: (id: number) => `${ROOTS.PORTFOLIO_THESIS}/${id}`,
  },
  portfolio_activity: {
    root: ROOTS.PORTFOLIO_ACTIVITY,
    list: `${ROOTS.PORTFOLIO_ACTIVITY}/`,
    detail: (id: number) => `${ROOTS.PORTFOLIO_ACTIVITY}/${id}`,
  },
  portfolio_skill: {
    root: ROOTS.PORTFOLIO_SKILL,
    works: `${ROOTS.PORTFOLIO_SKILL}/works`,
    detail: (id: number) => `${ROOTS.PORTFOLIO_SKILL}/${id}`,
    mapping: (id: number) => `${ROOTS.PORTFOLIO_SKILL}/mapping/${id}`,
    assign_work: `${ROOTS.PORTFOLIO_SKILL}/assign-work`,
    deleteMapping: (id: number) => `${ROOTS.PORTFOLIO_SKILL}/mapping/${id}`,
  },
  student_learning_activity_group: {
    root: ROOTS.STUDENT_LEARNING_ACTIVITY_GROUP,
    all: `${ROOTS.STUDENT_LEARNING_ACTIVITY_GROUP}/all`,
    without_group: `${ROOTS.STUDENT_LEARNING_ACTIVITY_GROUP}/without-group`,
  },
  gradebook: {
    root: ROOTS.GRADEBOOK,
    per_student: `${ROOTS.GRADEBOOK}/per-student`,
    per_activity: `${ROOTS.GRADEBOOK}/per-activity`,
  },
  course_material: {
    root: ROOTS.COURSE_MATERIAL,
  },
  evaluation: {
    root: ROOTS.EVALUATION,
    list: `${ROOTS.EVALUATION}/list`,
  },
  portfolio: {
    root: ROOTS.PORTFOLIO,
    list: `${ROOTS.PORTFOLIO}/`,
    detail: (id: number) => `${ROOTS.PORTFOLIO}/${id}`,
  },
};
