import { describe, expect, it } from "vitest";
import request from "supertest";
import app from "../src/app";
import {
  createActivity,
  createCourse,
  createLearningActivity,
  createLearningSubmission,
  createScoreWeight,
  createStudent,
  createSubmission,
  createTeacher,
  enrolStudent,
} from "./factories";
import { BASELINE } from "./seed";
import { sessionCookie } from "./helpers/session";
import { enrolledCourse, FAR_FUTURE, TERM } from "./helpers/classroom";

/**
 * What a student can read about their own studies — /student.
 *
 * Eight read handlers, split down the middle by where they get the student
 * from. Four take it from the session and are about *me*: /course/list,
 * /classwork/list, /all/classwork/list and the calendar (which has its own
 * file). Four take a student_id or a section_id from the query, have no
 * middleware at all, and will answer about anybody: /list, /enrolled/subjects,
 * /activities/list and /activities/details/:id. That difference is the single
 * most important thing in this group and every case below is written to make
 * it visible rather than to hide it.
 *
 * Submitting work lives in student-submit.test.ts, the calendar in
 * student-calendar.test.ts.
 */

describe("GET /student/list", () => {
  it("returns the students enrolled in a section, by id", async () => {
    const course = await createCourse();
    // Enrolled in the reverse of the order they come back in, so the sort is
    // doing the work rather than the insertion order. The ids are outside the
    // range nextStudentId() counts through, which every other case here uses.
    const second = await createStudent({
      student_id: "65009002",
      first_name_th: "สมปอง",
      last_name_th: "ตั้งใจ",
    });
    const first = await createStudent({
      student_id: "65009001",
      first_name_th: "สมหญิง",
      last_name_th: "เรียนดี",
    });
    await enrolStudent(course.section_id, second.student_id);
    await enrolStudent(course.section_id, first.student_id);

    const response = await request(app)
      .get("/student/list")
      .query({ section_id: course.section_id });

    expect(response.status).toBe(200);
    expect(
      response.body.data.map((s: { student_id: string }) => s.student_id),
    ).toEqual(["65009001", "65009002"]);
    expect(response.body.data[0]).toMatchObject({
      student_id: "65009001",
      first_name_th: "สมหญิง",
      last_name_th: "เรียนดี",
      // Both generated by Postgres and never written by the factory (T6):
      // the full name is the two name columns joined, and the admission year
      // is the first two digits of the id read as a Buddhist-era year.
      full_name_th: "สมหญิง เรียนดี",
      admission_year: "2565",
      status: "active",
    });
  });

  it("returns an empty list for a section nobody is enrolled in", async () => {
    const course = await createCourse();

    const response = await request(app)
      .get("/student/list")
      .query({ section_id: course.section_id });

    expect(response.status).toBe(200);
    expect(response.body.data).toEqual([]);
  });

  it("leaves out students enrolled in a different section", async () => {
    const course = await createCourse();
    const other = await createCourse();
    const mine = await createStudent();
    const theirs = await createStudent();
    await enrolStudent(course.section_id, mine.student_id);
    await enrolStudent(other.section_id, theirs.student_id);

    const response = await request(app)
      .get("/student/list")
      .query({ section_id: course.section_id });

    expect(
      response.body.data.map((s: { student_id: string }) => s.student_id),
    ).toEqual([mine.student_id]);
  });

  it("answers 500 when the section_id is missing", async () => {
    // parseInt(undefined) is NaN, which Prisma sends as null against a NOT NULL
    // column. Recorded for #12 and #13; #20 turns it into a 400.
    const response = await request(app).get("/student/list");

    expect(response.status).toBe(500);
    expect(response.body.success).toBe(false);
  });

  it("serves a request with no session", async () => {
    // No middleware: the whole roster of any section is readable by anyone who
    // can guess a section id. #31.
    const course = await createCourse();
    const student = await createStudent();
    await enrolStudent(course.section_id, student.student_id);

    const response = await request(app)
      .get("/student/list")
      .query({ section_id: course.section_id });

    expect(response.status).toBe(200);
    expect(response.body.data).toHaveLength(1);
  });
});

describe("GET /student/course/list", () => {
  it("returns the courses the signed-in student takes this term", async () => {
    const student = await createStudent();
    const course = await enrolledCourse(student.student_id, {
      subject_name_en: "Software Engineering",
      subject_name_th: "วิศวกรรมซอฟต์แวร์",
      schedule: { day_of_week: "TUE", start_time: "09:00", end_time: "12:00" },
    });

    const response = await request(app)
      .get("/student/course/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }))
      .query(TERM);

    expect(response.status).toBe(200);
    expect(response.body.data).toHaveLength(1);
    expect(response.body.data[0]).toMatchObject({
      section_id: course.section_id,
      course_name_en: "Software Engineering",
      course_name_th: "วิศวกรรมซอฟต์แวร์",
      day_of_week: "TUE",
      start_time: "09:00",
      end_time: "12:00",
    });
  });

  it("leaves out courses from another term", async () => {
    const student = await createStudent();
    const thisTerm = await enrolledCourse(student.student_id);
    await enrolledCourse(student.student_id, BASELINE.previousTerm);

    const response = await request(app)
      .get("/student/course/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }))
      .query(TERM);

    expect(
      response.body.data.map((c: { section_id: number }) => c.section_id),
    ).toEqual([thisTerm.section_id]);
  });

  it("leaves out a section nobody teaches", async () => {
    // getCourseDetail returns null without a teacher and the null is filtered
    // out, so an untaught section is invisible to the student enrolled in it.
    const student = await createStudent();
    const untaught = await createCourse();
    await enrolStudent(untaught.section_id, student.student_id);

    const response = await request(app)
      .get("/student/course/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }))
      .query(TERM);

    expect(response.status).toBe(200);
    expect(response.body.data).toEqual([]);
  });

  it("returns an empty list for a student enrolled in nothing", async () => {
    const student = await createStudent();

    const response = await request(app)
      .get("/student/course/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }))
      .query(TERM);

    expect(response.status).toBe(200);
    expect(response.body.data).toEqual([]);
  });

  it("refuses a request with no session", async () => {
    const response = await request(app)
      .get("/student/course/list")
      .query(TERM);

    expect(response.status).toBe(401);
    expect(response.body).toEqual({
      message: "ไม่พบ Token หรือ Token หมดอายุ",
    });
  });

  it("refuses a teacher", async () => {
    const teacher = await createTeacher();

    const response = await request(app)
      .get("/student/course/list")
      .set("Cookie", sessionCookie({ userId: teacher.user_id }))
      .query(TERM);

    expect(response.status).toBe(403);
    expect(response.body).toEqual({
      message: "สิทธิ์การเข้าถึงเฉพาะนักศึกษาเท่านั้น",
    });
  });
});

describe("GET /student/classwork/list", () => {
  it("groups a section's work under its score category", async () => {
    const student = await createStudent();
    const course = await enrolledCourse(student.student_id);
    const ratio = await createScoreWeight({
      section_id: course.section_id,
      score_category: "การบ้าน",
    });
    const activity = await createActivity({
      section_id: course.section_id,
      activity_name: "การบ้านครั้งที่ 1",
      score_weight_id: ratio.score_ratio_id,
      announcement_date: new Date("2020-01-01T00:00:00Z"),
      deadline_date: FAR_FUTURE,
    });
    await createSubmission({
      student_id: student.student_id,
      activity_id: activity.id,
      status: "NOT_SUBMITTED",
    });

    const response = await request(app)
      .get("/student/classwork/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }))
      .query({ section_id: course.section_id });

    expect(response.status).toBe(200);
    expect(response.body.data.today).toEqual([]);
    expect(response.body.data.other).toEqual([
      {
        title: "การบ้าน",
        classworks: [
          expect.objectContaining({
            name: "การบ้านครั้งที่ 1",
            category: "activity",
            status: "NOT_SUBMITTED",
          }),
        ],
      },
    ]);
  });

  it("files learning activities under their own heading", async () => {
    const student = await createStudent();
    const course = await enrolledCourse(student.student_id);
    const learningActivity = await createLearningActivity({
      section_id: course.section_id,
      learning_activity_name: "กิจกรรมกลุ่มครั้งที่ 1",
      announcement_date: new Date("2020-01-01T00:00:00Z"),
      deadline_date: FAR_FUTURE,
    });
    await createLearningSubmission({
      student_id: student.student_id,
      learning_activity_id: learningActivity.id,
    });

    const response = await request(app)
      .get("/student/classwork/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }))
      .query({ section_id: course.section_id });

    expect(response.body.data.other).toEqual([
      {
        title: "กิจกรรมการเรียนรู้",
        classworks: [
          expect.objectContaining({ name: "กิจกรรมกลุ่มครั้งที่ 1" }),
        ],
      },
    ]);
  });

  it("files work with no score category under อื่น ๆ", async () => {
    const student = await createStudent();
    const course = await enrolledCourse(student.student_id);
    const activity = await createActivity({
      section_id: course.section_id,
      announcement_date: new Date("2020-01-01T00:00:00Z"),
      deadline_date: FAR_FUTURE,
    });
    await createSubmission({
      student_id: student.student_id,
      activity_id: activity.id,
    });

    const response = await request(app)
      .get("/student/classwork/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }))
      .query({ section_id: course.section_id });

    expect(
      response.body.data.other.map((g: { title: string }) => g.title),
    ).toEqual(["อื่น ๆ"]);
  });

  it("puts work due today in its own bucket", async () => {
    const student = await createStudent();
    const course = await enrolledCourse(student.student_id);
    const activity = await createActivity({
      section_id: course.section_id,
      activity_name: "งานส่งวันนี้",
      announcement_date: new Date("2020-01-01T00:00:00Z"),
      deadline_date: new Date(),
    });
    await createSubmission({
      student_id: student.student_id,
      activity_id: activity.id,
    });

    const response = await request(app)
      .get("/student/classwork/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }))
      .query({ section_id: course.section_id });

    expect(response.body.data.today).toHaveLength(1);
    expect(response.body.data.today[0].name).toBe("งานส่งวันนี้");
    expect(response.body.data.other).toEqual([]);
  });

  it("returns empty groups for a section with no work in it", async () => {
    const student = await createStudent();
    const course = await enrolledCourse(student.student_id);

    const response = await request(app)
      .get("/student/classwork/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }))
      .query({ section_id: course.section_id });

    expect(response.status).toBe(200);
    expect(response.body.data).toEqual({ today: [], other: [] });
  });

  it("refuses a request with no session", async () => {
    const course = await createCourse();

    const response = await request(app)
      .get("/student/classwork/list")
      .query({ section_id: course.section_id });

    expect(response.status).toBe(401);
  });

  it("refuses a teacher", async () => {
    const teacher = await createTeacher();
    const course = await createCourse();

    const response = await request(app)
      .get("/student/classwork/list")
      .set("Cookie", sessionCookie({ userId: teacher.user_id }))
      .query({ section_id: course.section_id });

    expect(response.status).toBe(403);
  });
});

describe("GET /student/all/classwork/list", () => {
  it("sorts every section's work into late, this week, upcoming and submitted", async () => {
    const student = await createStudent();
    const course = await enrolledCourse(student.student_id);
    const announced = { announcement_date: new Date("2020-01-01T00:00:00Z") };

    const late = await createActivity({
      section_id: course.section_id,
      activity_name: "งานที่เลยกำหนด",
      deadline_date: new Date("2020-06-01T00:00:00Z"),
      ...announced,
    });
    await createSubmission({
      student_id: student.student_id,
      activity_id: late.id,
      status: "NOT_SUBMITTED",
    });

    const upcoming = await createActivity({
      section_id: course.section_id,
      activity_name: "งานที่ยังไม่ถึงกำหนด",
      deadline_date: FAR_FUTURE,
      ...announced,
    });
    await createSubmission({
      student_id: student.student_id,
      activity_id: upcoming.id,
      status: "NOT_SUBMITTED",
    });

    const done = await createActivity({
      section_id: course.section_id,
      activity_name: "งานที่ส่งแล้ว",
      deadline_date: new Date("2020-06-01T00:00:00Z"),
      ...announced,
    });
    await createSubmission({
      student_id: student.student_id,
      activity_id: done.id,
      status: "SUBMITTED",
    });

    const response = await request(app)
      .get("/student/all/classwork/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }))
      .query(TERM);

    expect(response.status).toBe(200);
    expect(response.body.data.late.map((c: { name: string }) => c.name)).toEqual(
      ["งานที่เลยกำหนด"],
    );
    expect(
      response.body.data.upcoming.map((c: { name: string }) => c.name),
    ).toEqual(["งานที่ยังไม่ถึงกำหนด"]);
    // Anything already handed in is "submitted" whatever its deadline says.
    expect(
      response.body.data.submitted.map((c: { name: string }) => c.name),
    ).toEqual(["งานที่ส่งแล้ว"]);
  });

  it("counts work with no deadline as upcoming", async () => {
    const student = await createStudent();
    const course = await enrolledCourse(student.student_id);
    const activity = await createActivity({
      section_id: course.section_id,
      activity_name: "งานที่ไม่มีกำหนดส่ง",
      announcement_date: new Date("2020-01-01T00:00:00Z"),
    });
    await createSubmission({
      student_id: student.student_id,
      activity_id: activity.id,
      status: "NOT_SUBMITTED",
    });

    const response = await request(app)
      .get("/student/all/classwork/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }))
      .query(TERM);

    expect(
      response.body.data.upcoming.map((c: { name: string }) => c.name),
    ).toEqual(["งานที่ไม่มีกำหนดส่ง"]);
  });

  it("returns four empty buckets for a student enrolled in nothing", async () => {
    const student = await createStudent();

    const response = await request(app)
      .get("/student/all/classwork/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }))
      .query(TERM);

    expect(response.status).toBe(200);
    expect(response.body.data).toEqual({
      late: [],
      this_week: [],
      upcoming: [],
      submitted: [],
    });
  });

  it("refuses a request with no session", async () => {
    const response = await request(app)
      .get("/student/all/classwork/list")
      .query(TERM);

    expect(response.status).toBe(401);
  });

  it("refuses a teacher", async () => {
    const teacher = await createTeacher();

    const response = await request(app)
      .get("/student/all/classwork/list")
      .set("Cookie", sessionCookie({ userId: teacher.user_id }))
      .query(TERM);

    expect(response.status).toBe(403);
  });
});

describe("GET /student/enrolled/subjects", () => {
  it("returns the subjects the named student is enrolled in", async () => {
    const student = await createStudent();
    const course = await enrolledCourse(student.student_id, {
      subject_name_en: "Data Structures",
      subject_name_th: "โครงสร้างข้อมูล",
    });

    const response = await request(app)
      .get("/student/enrolled/subjects")
      .query({ student_id: student.student_id });

    expect(response.status).toBe(200);
    expect(response.body.data).toEqual([
      {
        section_id: course.section_id,
        subject_name_en: "Data Structures",
        subject_name_th: "โครงสร้างข้อมูล",
      },
    ]);
  });

  it("returns every term, not just the current one", async () => {
    // Unlike /course/list, this one takes no term and filters by nothing.
    const student = await createStudent();
    await enrolledCourse(student.student_id);
    await enrolledCourse(student.student_id, BASELINE.previousTerm);

    const response = await request(app)
      .get("/student/enrolled/subjects")
      .query({ student_id: student.student_id });

    expect(response.body.data).toHaveLength(2);
  });

  it("returns an empty list for a student who is enrolled in nothing", async () => {
    const student = await createStudent();

    const response = await request(app)
      .get("/student/enrolled/subjects")
      .query({ student_id: student.student_id });

    expect(response.status).toBe(200);
    expect(response.body.data).toEqual([]);
  });

  it("answers about whoever the query names, with no session at all", async () => {
    // The gap this group's #31 is about, stated plainly: a classmate's
    // timetable is one query parameter away. Nothing here is a session.
    const classmate = await createStudent();
    await enrolledCourse(classmate.student_id);

    const response = await request(app)
      .get("/student/enrolled/subjects")
      .query({ student_id: classmate.student_id });

    expect(response.status).toBe(200);
    expect(response.body.data).toHaveLength(1);
  });

  it("returns every enrolment in the system when no student_id is sent", async () => {
    // `where: { student_id: undefined }` in a findMany is not an error the way
    // it is in a findUnique — it means "do not filter", so leaving the
    // parameter off hands back everybody's timetable rather than nobody's.
    // Same shape as GET /rubric/shared-rubric without a program_id, recorded
    // for #13; this endpoint has no session to fall back on either. #20.
    const classmate = await createStudent();
    const course = await enrolledCourse(classmate.student_id);

    const response = await request(app).get("/student/enrolled/subjects");

    expect(response.status).toBe(200);
    expect(
      response.body.data.map((s: { section_id: number }) => s.section_id),
    ).toContain(course.section_id);
  });

  it("answers 500 when student_id is sent twice", async () => {
    // Express parses a repeated query parameter into an array, and an array is
    // not something Prisma will compare a String column against. The only
    // failing case this endpoint has: everything else it is given, including
    // nothing at all, it answers.
    const student = await createStudent();

    const response = await request(app)
      .get("/student/enrolled/subjects")
      .query({ student_id: [student.student_id, "65000099"] });

    expect(response.status).toBe(500);
    expect(response.body.success).toBe(false);
  });
});

describe("GET /student/activities/list", () => {
  it("returns every activity in the section with this student's submission", async () => {
    const student = await createStudent();
    const course = await enrolledCourse(student.student_id);
    const graded = await createActivity({
      section_id: course.section_id,
      activity_name: "งานที่ตรวจแล้ว",
    });
    const untouched = await createActivity({
      section_id: course.section_id,
      activity_name: "งานที่ยังไม่ได้ส่ง",
    });
    const submission = await createSubmission({
      student_id: student.student_id,
      activity_id: graded.id,
      status: "GRADED",
      score: 8,
      feedback: "ทำได้ดี",
    });

    const response = await request(app)
      .get("/student/activities/list")
      .query({ section_id: course.section_id, student_id: student.student_id });

    expect(response.status).toBe(200);
    expect(response.body.data).toEqual([
      {
        activity_id: graded.id,
        activity_name: "งานที่ตรวจแล้ว",
        student_activity_id: submission.id,
        status: "GRADED",
        score: "8",
        feedback: "ทำได้ดี",
      },
      {
        // No submission row: the activity still appears, with nulls where the
        // student's own answer would be.
        activity_id: untouched.id,
        activity_name: "งานที่ยังไม่ได้ส่ง",
        student_activity_id: null,
        status: null,
        score: null,
        feedback: null,
      },
    ]);
  });

  it("shows nulls for a student who submitted nothing", async () => {
    const student = await createStudent();
    const classmate = await createStudent();
    const course = await enrolledCourse(student.student_id);
    const activity = await createActivity({ section_id: course.section_id });
    await createSubmission({
      student_id: classmate.student_id,
      activity_id: activity.id,
    });

    const response = await request(app)
      .get("/student/activities/list")
      .query({ section_id: course.section_id, student_id: student.student_id });

    expect(response.body.data).toEqual([
      {
        activity_id: activity.id,
        activity_name: "งานตัวอย่าง",
        student_activity_id: null,
        status: null,
        score: null,
        feedback: null,
      },
    ]);
  });

  it("returns an empty list when the section_id is missing", async () => {
    // A NaN in a findMany filter is only ever compared, never written, so
    // Prisma answers it rather than rejecting it — no section has that id, so
    // the caller gets 200 and nothing. The two sibling endpoints above answer
    // the same mistake with a 500, because theirs reaches a NOT NULL column.
    const student = await createStudent();
    await createActivity();

    const response = await request(app)
      .get("/student/activities/list")
      .query({ student_id: student.student_id });

    expect(response.status).toBe(200);
    expect(response.body.data).toEqual([]);
  });

  it("answers 500 for a section_id larger than an Int", async () => {
    // A number Prisma cannot narrow to the column's type is rejected before it
    // reaches Postgres, where NaN was not. The same trick #15 needed to give
    // GET /gradebook/per-activity a failing case, and for the same reason: an
    // endpoint that only ever compares can otherwise be handed anything.
    const student = await createStudent();

    const response = await request(app)
      .get("/student/activities/list")
      .query({ section_id: "99999999999", student_id: student.student_id });

    expect(response.status).toBe(500);
    expect(response.body.success).toBe(false);
  });
});

describe("GET /student/activities/details/:student_activity_id", () => {
  it("returns the submission with the course it belongs to", async () => {
    const student = await createStudent();
    const course = await enrolledCourse(student.student_id, {
      subject_name_en: "Data Structures",
      subject_name_th: "โครงสร้างข้อมูล",
    });
    const activity = await createActivity({
      section_id: course.section_id,
      activity_name: "งานตัวอย่าง",
    });
    const submission = await createSubmission({
      student_id: student.student_id,
      activity_id: activity.id,
      status: "GRADED",
      score: 9,
      feedback: "เรียบร้อยดี",
    });

    const response = await request(app).get(
      `/student/activities/details/${submission.id}`,
    );

    expect(response.status).toBe(200);
    expect(response.body.data).toMatchObject({
      id: submission.id,
      student_id: student.student_id,
      status: "GRADED",
      score: "9",
      feedback: "เรียบร้อยดี",
      course: {
        course_id: course.subject_id,
        course_name_en: "Data Structures",
        course_name_th: "โครงสร้างข้อมูล",
      },
    });
    expect(response.body.data.activities).toMatchObject({
      id: activity.id,
      activity_name: "งานตัวอย่าง",
    });
  });

  it("answers 404 for an id that belongs to no submission", async () => {
    const response = await request(app).get(
      "/student/activities/details/999999",
    );

    expect(response.status).toBe(404);
    expect(response.body).toEqual({
      success: false,
      message: "Student activity not found",
    });
  });

  it("answers 500 for an id that is not a number", async () => {
    // parseInt("abc") is NaN, and findUnique will not take one — unlike the
    // findMany above, a unique lookup rejects it outright. So the caller who
    // mistypes a URL is told the server broke rather than that the id is
    // wrong; #20 turns this into a 400.
    const response = await request(app).get("/student/activities/details/abc");

    expect(response.status).toBe(500);
    expect(response.body.success).toBe(false);
  });

  it("answers about anybody's submission, with no session", async () => {
    const classmate = await createStudent();
    const submission = await createSubmission({
      student_id: classmate.student_id,
      feedback: "ความเห็นถึงเพื่อนร่วมชั้น",
    });

    const response = await request(app).get(
      `/student/activities/details/${submission.id}`,
    );

    expect(response.status).toBe(200);
    expect(response.body.data.feedback).toBe("ความเห็นถึงเพื่อนร่วมชั้น");
  });
});
