import { describe, expect, it } from "vitest";
import request from "supertest";
import app from "../src/app";
import {
  createActivity,
  createCourse,
  createLearningActivity,
  createLearningSubmission,
  createScoreWeight,
  createStudent,
  createSubmission,
  createTeacher,
  enrolStudent,
} from "./factories";
import { BASELINE } from "./seed";
import { sessionCookie } from "./helpers/session";
import { enrolledCourse, FAR_FUTURE, TERM } from "./helpers/classroom";

/**
 * What a student can read about their own studies — /student.
 *
 * Eight read handlers. Six are about *me* and take the student from the
 * session: /course/list, /classwork/list, /all/classwork/list, the calendar
 * (which has its own file), /enrolled/subjects since #40, and /activities/list
 * since #41, which used to take a student_id from the query and hand back a
 * classmate's whole submission history. Of the two that still name something in
 * the request, /activities/details/:id names a row and must own it, and /list
 * names a section and belongs to the teacher who teaches it.
 *
 * All eight require a session now. The cases below are written so that which
 * rule guards which route is readable from the refusals themselves.
 *
 * Submitting work lives in student-submit.test.ts, the calendar in
 * student-calendar.test.ts.
 */

describe("GET /student/list", () => {
  it("returns the students enrolled in a section, by id", async () => {
    const teacher = await createTeacher();
    const course = await createCourse({ teacher_id: teacher.user_id });
    // Enrolled in the reverse of the order they come back in, so the sort is
    // doing the work rather than the insertion order. The ids are outside the
    // range nextStudentId() counts through, which every other case here uses.
    const second = await createStudent({
      student_id: "65009002",
      first_name_th: "สมปอง",
      last_name_th: "ตั้งใจ",
    });
    const first = await createStudent({
      student_id: "65009001",
      first_name_th: "สมหญิง",
      last_name_th: "เรียนดี",
    });
    await enrolStudent(course.section_id, second.student_id);
    await enrolStudent(course.section_id, first.student_id);

    const response = await request(app)
      .get("/student/list")
      .set("Cookie", sessionCookie({ userId: teacher.user_id }))
      .query({ section_id: course.section_id });

    expect(response.status).toBe(200);
    expect(
      response.body.data.map((s: { student_id: string }) => s.student_id),
    ).toEqual(["65009001", "65009002"]);
    // toEqual, not toMatchObject: four keys and no others is the point. The
    // query had no select until #68, so this used to be every column the
    // student table has — including admission_year, status, created_at,
    // updated_at, department_id, program_id and one named test. full_name_th
    // is generated by Postgres and never written by the factory (T6): it is
    // the two name columns joined.
    expect(response.body.data[0]).toEqual({
      student_id: "65009001",
      first_name_th: "สมหญิง",
      last_name_th: "เรียนดี",
      full_name_th: "สมหญิง เรียนดี",
    });
  });

  it("returns an empty list for a section nobody is enrolled in", async () => {
    const teacher = await createTeacher();
    const course = await createCourse({ teacher_id: teacher.user_id });

    const response = await request(app)
      .get("/student/list")
      .set("Cookie", sessionCookie({ userId: teacher.user_id }))
      .query({ section_id: course.section_id });

    expect(response.status).toBe(200);
    expect(response.body.data).toEqual([]);
  });

  it("leaves out students enrolled in a different section", async () => {
    const teacher = await createTeacher();
    const course = await createCourse({ teacher_id: teacher.user_id });
    const other = await createCourse({ teacher_id: teacher.user_id });
    const mine = await createStudent();
    const theirs = await createStudent();
    await enrolStudent(course.section_id, mine.student_id);
    await enrolStudent(other.section_id, theirs.student_id);

    const response = await request(app)
      .get("/student/list")
      .set("Cookie", sessionCookie({ userId: teacher.user_id }))
      .query({ section_id: course.section_id });

    expect(
      response.body.data.map((s: { student_id: string }) => s.student_id),
    ).toEqual([mine.student_id]);
  });

  it("answers 400 when the section_id is missing", async () => {
    // parseInt(undefined) was NaN, which Prisma sends as null against a NOT
    // NULL column — a 500 about a section the caller never named.
    const teacher = await createTeacher();

    const response = await request(app)
      .get("/student/list")
      .set("Cookie", sessionCookie({ userId: teacher.user_id }));

    expect(response.status).toBe(400);
    expect(response.body.errors).toEqual([
      { field: "section_id", location: "query", message: "ต้องระบุ" },
    ]);
  });

  it("refuses a request with no session", async () => {
    const teacher = await createTeacher();
    const course = await createCourse({ teacher_id: teacher.user_id });
    const student = await createStudent();
    await enrolStudent(course.section_id, student.student_id);

    const response = await request(app)
      .get("/student/list")
      .query({ section_id: course.section_id });

    // The whole roster of any section used to be readable by anyone who could
    // guess a section id — no middleware at all, pinned since #31 (#41).
    expect(response.status).toBe(401);
    expect(response.body.message).toBe("ไม่พบ Token หรือ Token หมดอายุ");
  });

  it("refuses a student", async () => {
    const teacher = await createTeacher();
    const course = await createCourse({ teacher_id: teacher.user_id });
    const student = await createStudent();
    await enrolStudent(course.section_id, student.student_id);

    const response = await request(app)
      .get("/student/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }))
      .query({ section_id: course.section_id });

    // A roster is the teacher's view of the class, and the only screen that
    // asks for it is the teacher's. A classmate in the same section is refused
    // as squarely as a stranger.
    expect(response.status).toBe(403);
    expect(response.body.message).toBe("สิทธิ์การเข้าถึงเฉพาะอาจารย์เท่านั้น");
  });

  it("refuses a teacher who does not teach the section", async () => {
    const colleague = await createTeacher();
    // The teacher of record is nobody the case names: what matters is only
    // that it is not the colleague whose session asks.
    const teacher = await createTeacher();
    const course = await createCourse({ teacher_id: teacher.user_id });
    const student = await createStudent();
    await enrolStudent(course.section_id, student.student_id);

    const response = await request(app)
      .get("/student/list")
      .set("Cookie", sessionCookie({ userId: colleague.user_id }))
      .query({ section_id: course.section_id });

    expect(response.status).toBe(403);
    expect(response.body.message).toBe(
      "คุณไม่มีสิทธิ์เข้าถึงข้อมูลของกลุ่มเรียนนี้",
    );
  });

  it("refuses a section that does not exist with the same 403", async () => {
    const teacher = await createTeacher();

    const response = await request(app)
      .get("/student/list")
      .set("Cookie", sessionCookie({ userId: teacher.user_id }))
      .query({ section_id: 999999 });

    // Not a 404: section ids are small integers, and a caller who could tell
    // "no such section" from "not mine" could walk the range. ADR-0002.
    expect(response.status).toBe(403);
    expect(response.body.message).toBe(
      "คุณไม่มีสิทธิ์เข้าถึงข้อมูลของกลุ่มเรียนนี้",
    );
  });
});

describe("GET /student/course/list", () => {
  it("returns the courses the signed-in student takes this term", async () => {
    const student = await createStudent();
    const course = await enrolledCourse(student.student_id, {
      subject_name_en: "Software Engineering",
      subject_name_th: "วิศวกรรมซอฟต์แวร์",
      schedule: { day_of_week: "TUE", start_time: "09:00", end_time: "12:00" },
    });

    const response = await request(app)
      .get("/student/course/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }))
      .query(TERM);

    expect(response.status).toBe(200);
    expect(response.body.data).toHaveLength(1);
    expect(response.body.data[0]).toMatchObject({
      section_id: course.section_id,
      course_name_en: "Software Engineering",
      course_name_th: "วิศวกรรมซอฟต์แวร์",
      day_of_week: "TUE",
      start_time: "09:00",
      end_time: "12:00",
    });
  });

  it("leaves out courses from another term", async () => {
    const student = await createStudent();
    const thisTerm = await enrolledCourse(student.student_id);
    await enrolledCourse(student.student_id, BASELINE.previousTerm);

    const response = await request(app)
      .get("/student/course/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }))
      .query(TERM);

    expect(
      response.body.data.map((c: { section_id: number }) => c.section_id),
    ).toEqual([thisTerm.section_id]);
  });

  it("keeps a section nobody teaches, with the teacher unnamed", async () => {
    // See BEHAVIOR-CHANGES.md. The course used to vanish from the list of the
    // student enrolled in it, because getCourseDetail answered null without a
    // teacher and the null was filtered out (#48). Who teaches the section is
    // not the student's business to sort out.
    const student = await createStudent();
    const untaught = await createCourse();
    await enrolStudent(untaught.section_id, student.student_id);

    const response = await request(app)
      .get("/student/course/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }))
      .query(TERM);

    expect(response.status).toBe(200);
    expect(response.body.data).toHaveLength(1);
    expect(response.body.data[0]).toMatchObject({
      section_id: untaught.section_id,
      teacher_id: null,
      teacher_name_th: null,
    });
  });

  it("returns an empty list for a student enrolled in nothing", async () => {
    const student = await createStudent();

    const response = await request(app)
      .get("/student/course/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }))
      .query(TERM);

    expect(response.status).toBe(200);
    expect(response.body.data).toEqual([]);
  });

  it("refuses a request with no session", async () => {
    const response = await request(app).get("/student/course/list").query(TERM);

    expect(response.status).toBe(401);
    expect(response.body).toEqual({
      success: false,
      message: "ไม่พบ Token หรือ Token หมดอายุ",
    });
  });

  it("refuses a teacher", async () => {
    const teacher = await createTeacher();

    const response = await request(app)
      .get("/student/course/list")
      .set("Cookie", sessionCookie({ userId: teacher.user_id }))
      .query(TERM);

    expect(response.status).toBe(403);
    expect(response.body).toEqual({
      success: false,
      message: "สิทธิ์การเข้าถึงเฉพาะนักศึกษาเท่านั้น",
    });
  });

  it("answers 400 for a request that names no term", async () => {
    // Both halves of the term are required rather than defaulted to the current
    // one: the endpoint has no idea which term is current, and parseInt(
    // undefined) put a NaN semester into the filter, which matches nothing.
    const student = await createStudent();

    const response = await request(app)
      .get("/student/course/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }));

    expect(response.status).toBe(400);
    expect(response.body.errors).toEqual([
      { field: "semester", location: "query", message: "ต้องระบุ" },
      { field: "academic_year", location: "query", message: "ต้องระบุ" },
    ]);
  });

  it("answers 400 for a semester that is not a number", async () => {
    const student = await createStudent();

    const response = await request(app)
      .get("/student/course/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }))
      .query({ ...TERM, semester: "เทอมต้น" });

    expect(response.status).toBe(400);
    expect(response.body.errors).toEqual([
      { field: "semester", location: "query", message: "ต้องเป็นตัวเลข" },
    ]);
  });
});

describe("GET /student/classwork/list", () => {
  it("groups a section's work under its score category", async () => {
    const student = await createStudent();
    const course = await enrolledCourse(student.student_id);
    const ratio = await createScoreWeight({
      section_id: course.section_id,
      score_category: "การบ้าน",
    });
    const activity = await createActivity({
      section_id: course.section_id,
      activity_name: "การบ้านครั้งที่ 1",
      score_weight_id: ratio.score_ratio_id,
      announcement_date: new Date("2020-01-01T00:00:00Z"),
      deadline_date: FAR_FUTURE,
    });
    await createSubmission({
      student_id: student.student_id,
      activity_id: activity.id,
      status: "NOT_SUBMITTED",
    });

    const response = await request(app)
      .get("/student/classwork/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }))
      .query({ section_id: course.section_id });

    expect(response.status).toBe(200);
    expect(response.body.data.today).toEqual([]);
    expect(response.body.data.other).toEqual([
      {
        title: "การบ้าน",
        classworks: [
          expect.objectContaining({
            name: "การบ้านครั้งที่ 1",
            category: "activity",
            status: "NOT_SUBMITTED",
          }),
        ],
      },
    ]);
  });

  it("sends the mark the student already has as a number", async () => {
    // received_point is student_activity.score, a Decimal(5,2), and the type
    // both sides of the wire declare for it is number (#33). The card that
    // prints it does `received_point && point ? ... : ...`, so a string used to
    // print through untouched — right for "18", wrong the moment the column's
    // second decimal place carries anything.
    const student = await createStudent();
    const course = await enrolledCourse(student.student_id);
    const activity = await createActivity({
      section_id: course.section_id,
      announcement_date: new Date("2020-01-01T00:00:00Z"),
      deadline_date: FAR_FUTURE,
    });
    await createSubmission({
      student_id: student.student_id,
      activity_id: activity.id,
      status: "GRADED",
      score: 7.25,
    });

    const response = await request(app)
      .get("/student/classwork/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }))
      .query({ section_id: course.section_id });

    expect(response.status).toBe(200);
    expect(response.body.data.other[0].classworks[0].received_point).toBe(7.25);
  });

  it("files learning activities under their own heading", async () => {
    const student = await createStudent();
    const course = await enrolledCourse(student.student_id);
    const learningActivity = await createLearningActivity({
      section_id: course.section_id,
      learning_activity_name: "กิจกรรมกลุ่มครั้งที่ 1",
      announcement_date: new Date("2020-01-01T00:00:00Z"),
      deadline_date: FAR_FUTURE,
    });
    await createLearningSubmission({
      student_id: student.student_id,
      learning_activity_id: learningActivity.id,
    });

    const response = await request(app)
      .get("/student/classwork/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }))
      .query({ section_id: course.section_id });

    expect(response.body.data.other).toEqual([
      {
        title: "กิจกรรมการเรียนรู้",
        classworks: [
          expect.objectContaining({ name: "กิจกรรมกลุ่มครั้งที่ 1" }),
        ],
      },
    ]);
  });

  it("sends a learning activity's own section and detail, not a placeholder", async () => {
    // Both used to be missing. The query behind this half selected neither
    // column, so the mapper read undefined for `detail` — which JSON.stringify
    // drops — and fell through to its `?? 0` for `section_id`, giving every
    // learning activity in every section the same fictitious id. The `as`
    // cast at the end of that map is what let it typecheck (#68).
    const student = await createStudent();
    const course = await enrolledCourse(student.student_id);
    const learningActivity = await createLearningActivity({
      section_id: course.section_id,
      learning_activity_name: "กิจกรรมที่มีรายละเอียด",
      announcement_date: new Date("2020-01-01T00:00:00Z"),
      deadline_date: FAR_FUTURE,
      detail: { type: "doc", content: [] },
    });
    await createLearningSubmission({
      student_id: student.student_id,
      learning_activity_id: learningActivity.id,
    });

    const response = await request(app)
      .get("/student/classwork/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }))
      .query({ section_id: course.section_id });

    expect(response.status).toBe(200);
    expect(response.body.data.other[0].classworks[0]).toMatchObject({
      section_id: course.section_id,
      detail: { type: "doc", content: [] },
    });
  });

  it("sends the three dates as strings, and the same one twice", async () => {
    // date and deadline_date are one value read once. The mapper used to hand
    // `date` a Date it had just built from the other, which res.json turned
    // back into the identical string — so the body has not changed, but the
    // type says string now and the two lists parse it back deliberately (#68).
    const student = await createStudent();
    const course = await enrolledCourse(student.student_id);
    const announced = new Date("2020-01-01T00:00:00Z");
    const activity = await createActivity({
      section_id: course.section_id,
      announcement_date: announced,
      deadline_date: FAR_FUTURE,
    });
    await createSubmission({
      student_id: student.student_id,
      activity_id: activity.id,
    });

    const response = await request(app)
      .get("/student/classwork/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }))
      .query({ section_id: course.section_id });

    expect(response.status).toBe(200);
    expect(response.body.data.other[0].classworks[0]).toMatchObject({
      date: FAR_FUTURE.toISOString(),
      deadline_date: FAR_FUTURE.toISOString(),
      announcement_date: announced.toISOString(),
    });
  });

  it("lists both kinds of work that were never given an announcement date", async () => {
    // The other side of ADR-0005, and the one place both twins are asked at
    // once: this endpoint reads the activity list and the learning-activity
    // list through the same gate, and a null date used to drop a row from
    // either of them for good.
    const student = await createStudent();
    const course = await enrolledCourse(student.student_id);
    const activity = await createActivity({
      section_id: course.section_id,
      activity_name: "การบ้านที่ไม่ได้ตั้งวันประกาศ",
      deadline_date: FAR_FUTURE,
    });
    await createSubmission({
      student_id: student.student_id,
      activity_id: activity.id,
    });
    const learningActivity = await createLearningActivity({
      section_id: course.section_id,
      learning_activity_name: "กิจกรรมที่ไม่ได้ตั้งวันประกาศ",
      deadline_date: FAR_FUTURE,
    });
    await createLearningSubmission({
      student_id: student.student_id,
      learning_activity_id: learningActivity.id,
    });

    const response = await request(app)
      .get("/student/classwork/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }))
      .query({ section_id: course.section_id });

    expect(response.status).toBe(200);
    expect(
      response.body.data.other.flatMap(
        (group: { classworks: { name: string }[] }) =>
          group.classworks.map((classwork) => classwork.name),
      ),
    ).toEqual([
      "การบ้านที่ไม่ได้ตั้งวันประกาศ",
      "กิจกรรมที่ไม่ได้ตั้งวันประกาศ",
    ]);
  });

  it("files work with no score category under อื่น ๆ", async () => {
    const student = await createStudent();
    const course = await enrolledCourse(student.student_id);
    const activity = await createActivity({
      section_id: course.section_id,
      announcement_date: new Date("2020-01-01T00:00:00Z"),
      deadline_date: FAR_FUTURE,
    });
    await createSubmission({
      student_id: student.student_id,
      activity_id: activity.id,
    });

    const response = await request(app)
      .get("/student/classwork/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }))
      .query({ section_id: course.section_id });

    expect(
      response.body.data.other.map((g: { title: string }) => g.title),
    ).toEqual(["อื่น ๆ"]);
  });

  it("puts work due today in its own bucket", async () => {
    const student = await createStudent();
    const course = await enrolledCourse(student.student_id);
    const activity = await createActivity({
      section_id: course.section_id,
      activity_name: "งานส่งวันนี้",
      announcement_date: new Date("2020-01-01T00:00:00Z"),
      deadline_date: new Date(),
    });
    await createSubmission({
      student_id: student.student_id,
      activity_id: activity.id,
    });

    const response = await request(app)
      .get("/student/classwork/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }))
      .query({ section_id: course.section_id });

    expect(response.body.data.today).toHaveLength(1);
    expect(response.body.data.today[0].name).toBe("งานส่งวันนี้");
    expect(response.body.data.other).toEqual([]);
  });

  it("returns empty groups for a section with no work in it", async () => {
    const student = await createStudent();
    const course = await enrolledCourse(student.student_id);

    const response = await request(app)
      .get("/student/classwork/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }))
      .query({ section_id: course.section_id });

    expect(response.status).toBe(200);
    expect(response.body.data).toEqual({ today: [], other: [] });
  });

  it("refuses a request with no session", async () => {
    const course = await createCourse();

    const response = await request(app)
      .get("/student/classwork/list")
      .query({ section_id: course.section_id });

    expect(response.status).toBe(401);
  });

  it("refuses a teacher", async () => {
    const teacher = await createTeacher();
    const course = await createCourse();

    const response = await request(app)
      .get("/student/classwork/list")
      .set("Cookie", sessionCookie({ userId: teacher.user_id }))
      .query({ section_id: course.section_id });

    expect(response.status).toBe(403);
  });

  it("answers 400 for a request with no section_id", async () => {
    const student = await createStudent();

    const response = await request(app)
      .get("/student/classwork/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }));

    expect(response.status).toBe(400);
    expect(response.body.errors).toEqual([
      { field: "section_id", location: "query", message: "ต้องระบุ" },
    ]);
  });
});

describe("GET /student/all/classwork/list", () => {
  it("sorts every section's work into late, this week, upcoming and submitted", async () => {
    const student = await createStudent();
    const course = await enrolledCourse(student.student_id);
    const announced = { announcement_date: new Date("2020-01-01T00:00:00Z") };

    const late = await createActivity({
      section_id: course.section_id,
      activity_name: "งานที่เลยกำหนด",
      deadline_date: new Date("2020-06-01T00:00:00Z"),
      ...announced,
    });
    await createSubmission({
      student_id: student.student_id,
      activity_id: late.id,
      status: "NOT_SUBMITTED",
    });

    const upcoming = await createActivity({
      section_id: course.section_id,
      activity_name: "งานที่ยังไม่ถึงกำหนด",
      deadline_date: FAR_FUTURE,
      ...announced,
    });
    await createSubmission({
      student_id: student.student_id,
      activity_id: upcoming.id,
      status: "NOT_SUBMITTED",
    });

    const done = await createActivity({
      section_id: course.section_id,
      activity_name: "งานที่ส่งแล้ว",
      deadline_date: new Date("2020-06-01T00:00:00Z"),
      ...announced,
    });
    await createSubmission({
      student_id: student.student_id,
      activity_id: done.id,
      status: "SUBMITTED",
    });

    const response = await request(app)
      .get("/student/all/classwork/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }))
      .query(TERM);

    expect(response.status).toBe(200);
    expect(
      response.body.data.late.map((c: { name: string }) => c.name),
    ).toEqual(["งานที่เลยกำหนด"]);
    expect(
      response.body.data.upcoming.map((c: { name: string }) => c.name),
    ).toEqual(["งานที่ยังไม่ถึงกำหนด"]);
    // Anything already handed in is "submitted" whatever its deadline says.
    expect(
      response.body.data.submitted.map((c: { name: string }) => c.name),
    ).toEqual(["งานที่ส่งแล้ว"]);
  });

  it("sends the mark on a graded activity, which it used not to send at all", async () => {
    // The twin of "sends the mark the student already has as a number" one
    // describe up. This endpoint's query did not select student_activity.score,
    // so the mapper read undefined and JSON.stringify dropped received_point
    // from every activity row here — while the same field, filled by the same
    // mapper, was on every row of the other list (#68).
    const student = await createStudent();
    const course = await enrolledCourse(student.student_id);
    const activity = await createActivity({
      section_id: course.section_id,
      activity_name: "งานที่ตรวจแล้ว",
      announcement_date: new Date("2020-01-01T00:00:00Z"),
      deadline_date: FAR_FUTURE,
    });
    await createSubmission({
      student_id: student.student_id,
      activity_id: activity.id,
      status: "GRADED",
      score: 7.25,
    });

    const response = await request(app)
      .get("/student/all/classwork/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }))
      .query(TERM);

    expect(response.status).toBe(200);
    expect(response.body.data.submitted[0]).toMatchObject({
      name: "งานที่ตรวจแล้ว",
      received_point: 7.25,
    });
  });

  it("counts work with no deadline as upcoming", async () => {
    const student = await createStudent();
    const course = await enrolledCourse(student.student_id);
    const activity = await createActivity({
      section_id: course.section_id,
      activity_name: "งานที่ไม่มีกำหนดส่ง",
      announcement_date: new Date("2020-01-01T00:00:00Z"),
    });
    await createSubmission({
      student_id: student.student_id,
      activity_id: activity.id,
      status: "NOT_SUBMITTED",
    });

    const response = await request(app)
      .get("/student/all/classwork/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }))
      .query(TERM);

    expect(
      response.body.data.upcoming.map((c: { name: string }) => c.name),
    ).toEqual(["งานที่ไม่มีกำหนดส่ง"]);
  });

  it("sorts work that was never given an announcement date like any other", async () => {
    // The widest read of the five the announcement gate stands in front of —
    // every section at once. A null date is announced (ADR-0005), so the work
    // lands in the bucket its deadline puts it in rather than nowhere.
    const student = await createStudent();
    const course = await enrolledCourse(student.student_id);
    const activity = await createActivity({
      section_id: course.section_id,
      activity_name: "การบ้านที่ไม่ได้ตั้งวันประกาศ",
      deadline_date: FAR_FUTURE,
    });
    await createSubmission({
      student_id: student.student_id,
      activity_id: activity.id,
      status: "NOT_SUBMITTED",
    });
    const learningActivity = await createLearningActivity({
      section_id: course.section_id,
      learning_activity_name: "กิจกรรมที่ไม่ได้ตั้งวันประกาศ",
      deadline_date: FAR_FUTURE,
    });
    await createLearningSubmission({
      student_id: student.student_id,
      learning_activity_id: learningActivity.id,
      status: "NOT_SUBMITTED",
    });

    const response = await request(app)
      .get("/student/all/classwork/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }))
      .query(TERM);

    expect(response.status).toBe(200);
    expect(
      response.body.data.upcoming.map((c: { name: string }) => c.name),
    ).toEqual([
      "การบ้านที่ไม่ได้ตั้งวันประกาศ",
      "กิจกรรมที่ไม่ได้ตั้งวันประกาศ",
    ]);
  });

  it("returns four empty buckets for a student enrolled in nothing", async () => {
    const student = await createStudent();

    const response = await request(app)
      .get("/student/all/classwork/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }))
      .query(TERM);

    expect(response.status).toBe(200);
    expect(response.body.data).toEqual({
      late: [],
      this_week: [],
      upcoming: [],
      submitted: [],
    });
  });

  it("refuses a request with no session", async () => {
    const response = await request(app)
      .get("/student/all/classwork/list")
      .query(TERM);

    expect(response.status).toBe(401);
  });

  it("refuses a teacher", async () => {
    const teacher = await createTeacher();

    const response = await request(app)
      .get("/student/all/classwork/list")
      .set("Cookie", sessionCookie({ userId: teacher.user_id }))
      .query(TERM);

    expect(response.status).toBe(403);
  });

  it("answers 400 for a request that names no term", async () => {
    const student = await createStudent();

    const response = await request(app)
      .get("/student/all/classwork/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }));

    expect(response.status).toBe(400);
    expect(response.body.errors).toEqual([
      { field: "semester", location: "query", message: "ต้องระบุ" },
      { field: "academic_year", location: "query", message: "ต้องระบุ" },
    ]);
  });
});

describe("GET /student/enrolled/subjects", () => {
  it("returns the subjects the signed-in student is enrolled in", async () => {
    const student = await createStudent();
    const course = await enrolledCourse(student.student_id, {
      subject_name_en: "Data Structures",
      subject_name_th: "โครงสร้างข้อมูล",
    });

    const response = await request(app)
      .get("/student/enrolled/subjects")
      .set("Cookie", sessionCookie({ userId: student.student_id }));

    expect(response.status).toBe(200);
    expect(response.body.data).toEqual([
      {
        section_id: course.section_id,
        subject_name_en: "Data Structures",
        subject_name_th: "โครงสร้างข้อมูล",
      },
    ]);
  });

  it("returns every term, not just the current one", async () => {
    // Unlike /course/list, this one takes no term and filters by nothing.
    const student = await createStudent();
    await enrolledCourse(student.student_id);
    await enrolledCourse(student.student_id, BASELINE.previousTerm);

    const response = await request(app)
      .get("/student/enrolled/subjects")
      .set("Cookie", sessionCookie({ userId: student.student_id }));

    expect(response.body.data).toHaveLength(2);
  });

  it("returns an empty list for a student who is enrolled in nothing", async () => {
    const student = await createStudent();

    const response = await request(app)
      .get("/student/enrolled/subjects")
      .set("Cookie", sessionCookie({ userId: student.student_id }));

    expect(response.status).toBe(200);
    expect(response.body.data).toEqual([]);
  });

  it("ignores a student_id in the query and answers for the session", async () => {
    // A classmate's timetable used to be one query parameter away, with no
    // session anywhere in the request. The parameter is gone (#40), and the
    // route reads whoever is signed in — sending it changes nothing.
    const student = await createStudent();
    const classmate = await createStudent();
    await enrolledCourse(classmate.student_id);

    const response = await request(app)
      .get("/student/enrolled/subjects")
      .set("Cookie", sessionCookie({ userId: student.student_id }))
      .query({ student_id: classmate.student_id });

    expect(response.status).toBe(200);
    expect(response.body.data).toEqual([]);
  });

  it("refuses a request with no session", async () => {
    const student = await createStudent();
    await enrolledCourse(student.student_id);

    const response = await request(app).get("/student/enrolled/subjects");

    expect(response.status).toBe(401);
    expect(response.body).toEqual({
      success: false,
      message: "ไม่พบ Token หรือ Token หมดอายุ",
    });
  });

  it("refuses a teacher", async () => {
    const teacher = await createTeacher();

    const response = await request(app)
      .get("/student/enrolled/subjects")
      .set("Cookie", sessionCookie({ userId: teacher.user_id }));

    expect(response.status).toBe(403);
    expect(response.body).toEqual({
      success: false,
      message: "สิทธิ์การเข้าถึงเฉพาะนักศึกษาเท่านั้น",
    });
  });
});

describe("GET /student/activities/list", () => {
  it("returns every activity in the section with this student's submission", async () => {
    const student = await createStudent();
    const course = await enrolledCourse(student.student_id);
    const graded = await createActivity({
      section_id: course.section_id,
      activity_name: "งานที่ตรวจแล้ว",
    });
    const untouched = await createActivity({
      section_id: course.section_id,
      activity_name: "งานที่ยังไม่ได้ส่ง",
    });
    const submission = await createSubmission({
      student_id: student.student_id,
      activity_id: graded.id,
      status: "GRADED",
      score: 8,
      feedback: "ทำได้ดี",
    });

    const response = await request(app)
      .get("/student/activities/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }))
      .query({ section_id: course.section_id });

    expect(response.status).toBe(200);
    expect(response.body.data).toEqual([
      {
        activity_id: graded.id,
        activity_name: "งานที่ตรวจแล้ว",
        student_activity_id: submission.id,
        status: "GRADED",
        score: 8,
        feedback: "ทำได้ดี",
      },
      {
        // No submission row: the activity still appears, with nulls where the
        // student's own answer would be.
        activity_id: untouched.id,
        activity_name: "งานที่ยังไม่ได้ส่ง",
        student_activity_id: null,
        status: null,
        score: null,
        feedback: null,
      },
    ]);
  });

  it("shows nulls when the signed-in student submitted nothing", async () => {
    const student = await createStudent();
    const classmate = await createStudent();
    const course = await enrolledCourse(student.student_id);
    await enrolStudent(course.section_id, classmate.student_id);
    const activity = await createActivity({ section_id: course.section_id });
    await createSubmission({
      student_id: classmate.student_id,
      activity_id: activity.id,
    });

    const response = await request(app)
      .get("/student/activities/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }))
      .query({ section_id: course.section_id });

    // The classmate's submission is in the same section and is not what this
    // answers about: the student comes from the session now (#41).
    expect(response.body.data).toEqual([
      {
        activity_id: activity.id,
        activity_name: "งานตัวอย่าง",
        student_activity_id: null,
        status: null,
        score: null,
        feedback: null,
      },
    ]);
  });

  it("answers 400 when the section_id is missing", async () => {
    // A NaN in a findMany filter is only ever compared, never written, so
    // Prisma used to answer it rather than reject it: the caller got 200 and an
    // empty list, which reads as "this section has no work in it" for a section
    // they never named.
    const student = await createStudent();
    await createActivity();

    const response = await request(app)
      .get("/student/activities/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }));

    expect(response.status).toBe(400);
    expect(response.body.errors).toEqual([
      { field: "section_id", location: "query", message: "ต้องระบุ" },
    ]);
  });

  it("answers 400 for a section_id larger than an Int", async () => {
    // A number Prisma cannot narrow to the column's type used to be rejected
    // deep in the query, where NaN was not — so the same wrong parameter got a
    // 200 or a 500 depending on how wrong it was.
    const student = await createStudent();

    const response = await request(app)
      .get("/student/activities/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }))
      .query({ section_id: "99999999999" });

    expect(response.status).toBe(400);
    expect(response.body.errors).toEqual([
      {
        field: "section_id",
        location: "query",
        message: "ต้องไม่เกิน 2147483647",
      },
    ]);
  });

  it("ignores a student_id the caller sends anyway", async () => {
    const student = await createStudent();
    const classmate = await createStudent();
    const course = await enrolledCourse(student.student_id);
    await enrolStudent(course.section_id, classmate.student_id);
    const activity = await createActivity({ section_id: course.section_id });
    await createSubmission({
      student_id: classmate.student_id,
      activity_id: activity.id,
      status: "GRADED",
      score: 10,
      feedback: "ความเห็นถึงเพื่อนร่วมชั้น",
    });

    const response = await request(app)
      .get("/student/activities/list")
      .set("Cookie", sessionCookie({ userId: student.student_id }))
      .query({
        section_id: course.section_id,
        student_id: classmate.student_id,
      });

    // The parameter is gone from the schema, and zod strips what it does not
    // know — so naming a classmate is not refused, it is simply not read. What
    // comes back is still the caller's own row, which is empty here.
    expect(response.status).toBe(200);
    expect(response.body.data).toEqual([
      {
        activity_id: activity.id,
        activity_name: "งานตัวอย่าง",
        student_activity_id: null,
        status: null,
        score: null,
        feedback: null,
      },
    ]);
  });

  it("refuses a request with no session", async () => {
    const student = await createStudent();
    const course = await enrolledCourse(student.student_id);
    await createActivity({ section_id: course.section_id });

    const response = await request(app)
      .get("/student/activities/list")
      .query({ section_id: course.section_id });

    expect(response.status).toBe(401);
    expect(response.body.message).toBe("ไม่พบ Token หรือ Token หมดอายุ");
  });

  it("refuses a student who is not enrolled in the section", async () => {
    const stranger = await createStudent();
    const student = await createStudent();
    const course = await enrolledCourse(student.student_id);
    await createActivity({ section_id: course.section_id });

    const response = await request(app)
      .get("/student/activities/list")
      .set("Cookie", sessionCookie({ userId: stranger.student_id }))
      .query({ section_id: course.section_id });

    // Without this the answer would be an empty list rather than a refusal —
    // which reads as "this section has no work in it" for a class they are not
    // in, and still confirms the section exists.
    expect(response.status).toBe(403);
    expect(response.body.message).toBe(
      "คุณไม่มีสิทธิ์เข้าถึงข้อมูลของกลุ่มเรียนนี้",
    );
  });

  it("refuses a teacher", async () => {
    const teacher = await createTeacher();
    const student = await createStudent();
    const course = await enrolledCourse(student.student_id, {
      teacher_id: teacher.user_id,
    });
    await createActivity({ section_id: course.section_id });

    // This read is "the work in this section, with my own answers beside it",
    // and a teacher has no row of their own in it. What they need is the
    // gradebook, which is a different endpoint with a different shape.
    const response = await request(app)
      .get("/student/activities/list")
      .set("Cookie", sessionCookie({ userId: teacher.user_id }))
      .query({ section_id: course.section_id });

    expect(response.status).toBe(403);
    expect(response.body.message).toBe("สิทธิ์การเข้าถึงเฉพาะนักศึกษาเท่านั้น");
  });
});

describe("GET /student/activities/details/:student_activity_id", () => {
  it("returns the submission with the course it belongs to", async () => {
    const student = await createStudent();
    const course = await enrolledCourse(student.student_id, {
      subject_name_en: "Data Structures",
      subject_name_th: "โครงสร้างข้อมูล",
    });
    const activity = await createActivity({
      section_id: course.section_id,
      activity_name: "งานตัวอย่าง",
    });
    const submission = await createSubmission({
      student_id: student.student_id,
      activity_id: activity.id,
      status: "GRADED",
      score: 9,
      feedback: "เรียบร้อยดี",
    });

    const response = await request(app)
      .get(`/student/activities/details/${submission.id}`)
      .set("Cookie", sessionCookie({ userId: student.student_id }));

    expect(response.status).toBe(200);
    expect(response.body.data).toMatchObject({
      id: submission.id,
      student_id: student.student_id,
      status: "GRADED",
      score: 9,
      feedback: "เรียบร้อยดี",
      course: {
        course_id: course.subject_id,
        course_name_en: "Data Structures",
        course_name_th: "โครงสร้างข้อมูล",
      },
    });
    expect(response.body.data.activities).toMatchObject({
      id: activity.id,
      activity_name: "งานตัวอย่าง",
    });
  });

  it("sends ten fields, three off the activity, and the course — nothing else", async () => {
    // toEqual on the key sets, because what left is the point. The query had
    // no select and an include four tables deep, so this used to answer
    // graded_by, created_at and updated_at off the row, every column of
    // activities, and subject_score_ratio → course_sections →
    // semester_courses → subjects in full — a second road to the same subject
    // the `course` key already names (#68, ADR-0044 §1).
    const student = await createStudent();
    const course = await enrolledCourse(student.student_id);
    const activity = await createActivity({ section_id: course.section_id });
    const submission = await createSubmission({
      student_id: student.student_id,
      activity_id: activity.id,
    });

    const response = await request(app)
      .get(`/student/activities/details/${submission.id}`)
      .set("Cookie", sessionCookie({ userId: student.student_id }));

    expect(response.status).toBe(200);
    expect(Object.keys(response.body.data).sort()).toEqual([
      "activities",
      "activity_id",
      "course",
      "feedback",
      "graded_at",
      "id",
      "is_bookmark",
      "remark",
      "score",
      "status",
      "student_id",
      "submitted_at",
    ]);
    expect(Object.keys(response.body.data.activities).sort()).toEqual([
      "activity_name",
      "id",
      "section_id",
    ]);
  });

  it("leaves the course key out when the activity names no section", async () => {
    // Absent, not null: the service only adds the key inside the branch that
    // found a section, and JSON.stringify writes nothing for a key that was
    // never set (ADR-0033).
    const student = await createStudent();
    const activity = await createActivity({ section_id: null });
    const submission = await createSubmission({
      student_id: student.student_id,
      activity_id: activity.id,
    });

    const response = await request(app)
      .get(`/student/activities/details/${submission.id}`)
      .set("Cookie", sessionCookie({ userId: student.student_id }));

    expect(response.status).toBe(200);
    expect(response.body.data).not.toHaveProperty("course");
    expect(response.body.data.activities.section_id).toBeNull();
  });

  it("answers 404 for an id that belongs to no submission", async () => {
    const student = await createStudent();

    const response = await request(app)
      .get("/student/activities/details/999999")
      .set("Cookie", sessionCookie({ userId: student.student_id }));

    // Still a 404 rather than the 403 below: the ownership check reads the row
    // first and lets a missing one through, so "there is no such submission"
    // and "it is not yours" stay different answers here. ADR-0001.
    expect(response.status).toBe(404);
    expect(response.body).toEqual({
      success: false,
      message: "ไม่พบงานที่ต้องการ",
    });
  });

  it("answers 400 for an id that is not a number", async () => {
    // parseInt("abc") is NaN, and findUnique will not take one — unlike the
    // findMany above, a unique lookup rejects it outright. So the caller who
    // mistyped a URL used to be told the server broke rather than that the id
    // is wrong.
    const student = await createStudent();

    const response = await request(app)
      .get("/student/activities/details/abc")
      .set("Cookie", sessionCookie({ userId: student.student_id }));

    expect(response.status).toBe(400);
    expect(response.body.errors).toEqual([
      {
        field: "student_activity_id",
        location: "params",
        message: "ต้องเป็นตัวเลข",
      },
    ]);
  });

  it("refuses a request with no session", async () => {
    const classmate = await createStudent();
    const submission = await createSubmission({
      student_id: classmate.student_id,
      feedback: "ความเห็นถึงเพื่อนร่วมชั้น",
    });

    const response = await request(app).get(
      `/student/activities/details/${submission.id}`,
    );

    // Anybody's submission, feedback and score included, used to be one guessed
    // id away with no session at all (#41).
    expect(response.status).toBe(401);
    expect(response.body.message).toBe("ไม่พบ Token หรือ Token หมดอายุ");
  });

  it("refuses another student's submission", async () => {
    const classmate = await createStudent();
    const student = await createStudent();
    const submission = await createSubmission({
      student_id: classmate.student_id,
      feedback: "ความเห็นถึงเพื่อนร่วมชั้น",
    });

    const response = await request(app)
      .get(`/student/activities/details/${submission.id}`)
      .set("Cookie", sessionCookie({ userId: student.student_id }));

    expect(response.status).toBe(403);
    expect(response.body.message).toBe(
      "คุณไม่มีสิทธิ์เข้าถึงข้อมูลของผู้ใช้อื่น",
    );
  });

  it("refuses a teacher", async () => {
    const teacher = await createTeacher();
    const student = await createStudent();
    const submission = await createSubmission({
      student_id: student.student_id,
    });

    // The teacher's screens read a submission through /student-activity, which
    // is a different endpoint. This one is the student's own view of their own
    // work, and nothing on the teacher's side calls it.
    const response = await request(app)
      .get(`/student/activities/details/${submission.id}`)
      .set("Cookie", sessionCookie({ userId: teacher.user_id }));

    expect(response.status).toBe(403);
    expect(response.body.message).toBe("สิทธิ์การเข้าถึงเฉพาะนักศึกษาเท่านั้น");
  });
});
