import { describe, expect, it } from "vitest";
import request from "supertest";
import app from "../src/app";
import { createStudent, createTeacher, createUser } from "./factories";
import { BASELINE } from "./seed";
import { sessionCookie } from "./helpers/session";

/**
 * Who the caller is — /user.
 *
 * Two handlers that look alike and are not. GET /user takes an id from the
 * query, has no middleware at all, and hands back the whole `users` row to
 * anybody who asks. GET /user/student ignores the query entirely, takes the id
 * from the session, and returns a narrowed profile assembled from four tables.
 *
 * The generated columns matter here (T6). student.full_name_th is stored by
 * Postgres as first_name_th + last_name_th, so it is read back rather than
 * written, and no test may set it.
 */

describe("GET /user", () => {
  it("returns the user the id names", async () => {
    const user = await createTeacher({
      first_name_th: "สมชาย",
      last_name_th: "ใจดี",
      email: "somchai@example.test",
      phone: "021112222",
    });

    const response = await request(app)
      .get("/user")
      .query({ id: user.user_id });

    expect(response.status).toBe(200);
    expect(response.body.message).toBe("Fetched user successfully");
    expect(response.body.data).toMatchObject({
      user_id: user.user_id,
      email: "somchai@example.test",
      phone: "021112222",
      first_name_th: "สมชาย",
      last_name_th: "ใจดี",
      department_id: BASELINE.department.department_id,
      program_id: BASELINE.program.program_id,
    });
  });

  it("answers 200 with null for an id that belongs to nobody", async () => {
    // findUnique returning null is not an error here, so the caller gets a
    // success envelope wrapped around nothing rather than a 404. #20 is where
    // the missing-row conventions get settled.
    const response = await request(app)
      .get("/user")
      .query({ id: "99999999" });

    expect(response.status).toBe(200);
    expect(response.body).toEqual({
      success: true,
      message: "Fetched user successfully",
      data: null,
    });
  });

  it("answers 400 when no id is sent at all", async () => {
    // Not the same as an id that matches nobody. The parameter used to reach
    // Prisma as `where: { user_id: undefined }`, which is not a question it
    // will answer, so the caller got a 500.
    await createTeacher();

    const response = await request(app).get("/user");

    expect(response.status).toBe(400);
    expect(response.body).toEqual({
      success: false,
      message: "ข้อมูลที่ส่งมาไม่ถูกต้อง: id ต้องระบุ",
      errors: [{ field: "id", location: "query", message: "ต้องระบุ" }],
    });
  });

  it("serves a request with no session", async () => {
    // No middleware on this route: anyone who can guess an eight-character id
    // reads that person's name, email and phone number. That is #31's remit,
    // not something this ticket changes — the case is here so the hole is
    // visible rather than implied.
    const user = await createTeacher();

    const response = await request(app)
      .get("/user")
      .query({ id: user.user_id });

    expect(response.status).toBe(200);
    expect(response.body.data.email).toBe(user.email);
  });
});

describe("GET /user/student", () => {
  it("returns the signed-in student's profile", async () => {
    const student = await createStudent({
      first_name_th: "สมหญิง",
      last_name_th: "เรียนดี",
      title_th: "น.ส.",
      email: "somying@example.test",
      phone: "023334444",
    });

    const response = await request(app)
      .get("/user/student")
      .set("Cookie", sessionCookie({ userId: student.student_id }));

    expect(response.status).toBe(200);
    expect(response.body.message).toBe("Fetched student successfully");
    expect(response.body.data).toEqual({
      user_id: student.student_id,
      student_id: student.student_id,
      // Generated by Postgres from the two name columns — never written.
      full_name_th: "สมหญิง เรียนดี",
      first_name_th: "สมหญิง",
      last_name_th: "เรียนดี",
      title_th: "น.ส.",
      email: "somying@example.test",
      phone: "023334444",
      department_name: BASELINE.department.department_name_th,
      program_name: BASELINE.program.program_name_th,
    });
  });

  it("ignores an id in the query and answers for the session", async () => {
    const student = await createStudent({ first_name_th: "สมหญิง" });
    const classmate = await createStudent({ first_name_th: "สมปอง" });

    const response = await request(app)
      .get("/user/student")
      .set("Cookie", sessionCookie({ userId: student.student_id }))
      .query({ id: classmate.student_id, student_id: classmate.student_id });

    expect(response.body.data.student_id).toBe(student.student_id);
    expect(response.body.data.first_name_th).toBe("สมหญิง");
  });

  it("answers 200 with null for a student row that does not exist", async () => {
    // requireRole only proves the STUDENT role is granted, and the role lives
    // on `users` — a user can hold it without ever having a `student` row.
    const user = await createUser({ roles: ["STUDENT"] });

    const response = await request(app)
      .get("/user/student")
      .set("Cookie", sessionCookie({ userId: user.user_id }));

    expect(response.status).toBe(200);
    expect(response.body.data).toBeNull();
  });

  it("refuses a request with no session", async () => {
    const response = await request(app).get("/user/student");

    expect(response.status).toBe(401);
    expect(response.body).toEqual({
      success: false,
      message: "ไม่พบ Token หรือ Token หมดอายุ",
    });
  });

  it("refuses a teacher", async () => {
    const teacher = await createTeacher();

    const response = await request(app)
      .get("/user/student")
      .set("Cookie", sessionCookie({ userId: teacher.user_id }));

    expect(response.status).toBe(403);
    expect(response.body).toEqual({
      success: false,
      message: "สิทธิ์การเข้าถึงเฉพาะนักศึกษาเท่านั้น",
    });
  });

  it("refuses a token this server did not sign", async () => {
    const student = await createStudent();

    const response = await request(app)
      .get("/user/student")
      .set(
        "Cookie",
        sessionCookie({
          userId: student.student_id,
          secret: "not-the-servers-secret",
        }),
      );

    expect(response.status).toBe(401);
  });

  it("refuses an expired token", async () => {
    const student = await createStudent();

    const response = await request(app)
      .get("/user/student")
      .set(
        "Cookie",
        sessionCookie({ userId: student.student_id, expiresIn: "-1s" }),
      );

    expect(response.status).toBe(401);
  });
});
